describe('public privacy policy', () => {
  it('links from home and supports direct loading on narrow screens', () => {
    cy.visit('/')
    cy.get('.landing__footer').contains('a', 'Privacy policy').click()
    cy.location('pathname').should('eq', '/privacy')
    cy.title().should('eq', 'Privacy policy · Upside Down')
    cy.get('h1').should('have.text', 'Upside Down privacy policy')
    cy.get('article').should('contain.text', '90 days').and('not.contain.text', 'Publication draft')
    cy.get('a[href="mailto:iamprathamvaidya@gmail.com"]').should('be.visible')
    cy.viewport(320, 568)
    cy.visit('/privacy/')
    cy.get('nav').contains('a', 'Your controls').click()
    cy.location('hash').should('eq', '#your-controls')
    cy.get('#your-controls').should('be.visible')
    cy.document().then((doc) => expect(doc.documentElement.scrollWidth).to.be.at.most(320))
    cy.screenshot('privacy-mobile')
    cy.viewport(1280, 900)
    cy.visit('/privacy')
    cy.screenshot('privacy-desktop')
  })
})
