describe('room setup', () => {
  it('lets the host choose, resume after refresh, and start with saved settings', () => {
    cy.task<string>('room:open').then((code) => {
      cy.visit(`/r/${code}`)
      cy.joinRoom(code, 'Host')
      cy.get('[data-testid="setup-open"]').click()
      cy.get('[data-testid="region-in"]').click().should('have.attr', 'aria-pressed', 'true')
      cy.get('[data-testid="roast-slider"]').focus()
      cy.press(Cypress.Keyboard.Keys.END)
      cy.get('[data-testid="roast-slider"]').should('have.value', '3')
      cy.reload()
      cy.get('[data-testid="region-in"]').should('have.attr', 'aria-pressed', 'true')
      cy.get('[data-testid="roast-slider"]').should('have.value', '3')
      cy.screenshot('room-setup-phone', { capture: 'fullPage' })
      cy.get('[data-testid="setup-done"]').click()
      cy.get('[data-testid="settings-summary"]')
        .should('contain', 'India')
        .and('contain', 'Meet in Hell together')
      cy.task('bots:seat', { code, count: 2 })
      cy.get('[data-testid="start"]').click()
      cy.phase('writing')
      cy.get('[data-testid="setup-open"]').should('not.exist')
    })
  })

  it('shows the host choices on the stage live, then restores the room code', () => {
    cy.viewport(1280, 720)
    cy.visit('/stage')
    cy.readRoomCode().then((code) => {
      cy.task('bots:seat', { code, count: 1 })
      cy.task('bots:settings', { code, region: 'uk', level: 2, open: true })
      cy.get('[data-testid="room-setup"]').should('be.visible')
      cy.get('[data-selected="true"]').should('contain', 'UK').and('contain', 'Medium roast')
      cy.get('[data-testid="room-setup"] button').should('not.exist')
      cy.screenshot('room-setup-stage')
      cy.task('bots:settings', { code, region: 'us', level: 1, open: true })
      cy.get('[data-selected="true"]').should('contain', 'US').and('contain', 'HR approved')
      cy.task('bots:settings', { code, region: 'us', level: 1, open: false })
      cy.get('[data-testid="room-code"]').should('be.visible')
      cy.get('[data-testid="settings-summary"]').should('contain', 'US')
    })
  })

  it('shows guests the settings without host controls', () => {
    cy.task<string>('room:open').then((code) => {
      cy.task('bots:seat', { code, count: 1 })
      cy.task('bots:settings', { code, region: 'in', level: 2, open: true })
      cy.visit(`/r/${code}`)
      cy.joinRoom(code, 'Guest')
      cy.get('[data-testid="settings-summary"]').should('contain', 'India')
      cy.get('[data-testid="setup-open"]').should('not.exist')
      cy.get('[data-testid="room-setup"]').should('not.exist')
    })
  })
})
